---
name: Build and Run

on:
  pull_request:
    branches: [ master, develop ]

jobs:
  build-on-amd64:
    runs-on: ubuntu-20.04
    name: Build release binary on amd64

    steps:
    - uses: actions/checkout@v2

    - name: Build
      run: make build

  build-on-other:
    runs-on: ubuntu-18.04
    name: Build release binary on ${{ matrix.arch }} ${{ matrix.distro }}

    strategy:
      matrix:
        include:
          - arch: armv6
            distro: alpine_latest
          - arch: armv7
            distro: alpine_latest
          - arch: aarch64
            distro: alpine_latest
          - arch: s390x
            distro: alpine_latest
          - arch: ppc64le
            distro: alpine_latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2.1.1

      - name: Build on ${{ matrix.arch }} ${{ matrix.distro }}
        uses: uraimo/run-on-arch-action@v2.1.1
        id: runcmd
        with:
          arch: ${{ matrix.arch }}
          distro: ${{ matrix.distro }}

          install: |
            apk add --update make
            apk add --update g++

          run: make build
